import { ClerkProvider } from "@clerk/nextjs/app-beta";
import MainLayout from "@/components/ui/layouts/MainLayout";
import "styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-100">
        <ClerkProvider>
          <div>
            <MainLayout>{children}</MainLayout>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
